import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, BrainCircuit, BriefcaseBusiness, Code2, Compass, ShieldCheck, Sparkles } from "lucide-react";
import { Signature } from "@/components/brand/signature";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title: "من نحن", description: "قصة منصة آفاق الرقمية ورؤية مطورها عدناني." };

export default function AboutPage() {
  return <div className="container-shell py-14 sm:py-20"><section className="relative overflow-hidden rounded-[34px] border border-[var(--line)] bg-[var(--card)] p-7 sm:p-12 lg:p-16"><div className="grid-surface absolute inset-0 opacity-35" /><div className="relative max-w-3xl"><span className="badge text-[var(--brand)]"><Compass className="h-3.5 w-3.5" /> قصتنا</span><h1 className="font-display mt-6 text-3xl font-bold leading-[1.65] sm:text-5xl">من خبرة الواقع إلى أدوات تخدم الناس</h1><p className="mt-6 text-lg leading-9 text-[var(--muted)]">منصة آفاق الرقمية مشروع عربي مستقل من تطوير عدناني، يهدف إلى جمع أدوات عملية عالية الجودة في مكان واحد، بواجهة واضحة وبنية تنمو مع الاحتياج.</p><Signature className="mt-7" /></div></section><section className="grid gap-8 py-16 lg:grid-cols-[.85fr_1.15fr] lg:items-start sm:py-24"><SectionHeading eyebrow="عن المطور" title="عدناني: خبرة ميدانية تتجه إلى التقنية" description="يمتلك عدناني خبرة ميدانية تمتد إلى 12 عامًا في الأمن العام وحماية المنشآت، ويدرس حاليًا دبلوم الذكاء الاصطناعي التوليدي. يعمل على توظيف ما يتعلمه لبناء أدوات عربية عملية، لا على تقديم وعود مبالغ فيها." /><div className="grid gap-4 sm:grid-cols-2">{[[ShieldCheck, "12 عامًا ميدانيًا", "خبرة في الأمن وحماية المنشآت وفهم الاحتياج العملي."], [BrainCircuit, "ذكاء اصطناعي توليدي", "دراسة مستمرة لتحويل التقنية إلى حلول قابلة للاستخدام."], [Code2, "بناء وتطوير", "منصة مستقلة ببنية حسابات وأدوات قابلة للتوسع."], [BriefcaseBusiness, "تفكير خدمي", "أدوات تخدم الأفراد والطلاب والمطورين والشركات."]].map(([Icon, title, text]) => <div key={String(title)} className="glass-panel rounded-[22px] p-5"><Icon className="h-5 w-5 text-[var(--brand)]" /><h2 className="mt-4 font-bold">{String(title)}</h2><p className="mt-2 text-sm leading-7 text-[var(--muted)]">{String(text)}</p></div>)}</div></section><section className="glass-panel rounded-[30px] p-7 text-center sm:p-12"><Sparkles className="mx-auto h-7 w-7 text-[var(--gold)]" /><h2 className="font-display mt-5 text-2xl font-bold">الرؤية: أفق واحد، أدوات كثيرة، معيار واحد للجودة</h2><p className="mx-auto mt-4 max-w-2xl leading-8 text-[var(--muted)]">أن تعمل كل أداة فعلًا، وأن يعرف المستخدم كيف عولج ملفه، وأن تكون المنصة جاهزة لإضافة خدمات جديدة دون التضحية بالأمان أو سهولة الاستخدام.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/tools" className="btn-primary">استكشف الأدوات <ArrowLeft className="h-4 w-4" /></Link><Link href="/contact" className="btn-secondary">تواصل مع عدناني</Link></div></section></div>;
}
