import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, Save, Wrench } from "lucide-react";
import { getCurrentUser } from "@/lib/auth";
import { featureFlags } from "@/lib/brand";
import { demoOwner } from "@/lib/demo-data";
import { toolRegistry } from "@/lib/tool-registry";
import { updateToolRegistryAction } from "@/features/admin/actions";

export default async function AdminToolsPage() {
  const realUser = await getCurrentUser(); const user = realUser ?? (featureFlags.demoMode ? demoOwner : null);
  if (!user) redirect("/login?next=/admin/tools");
  if (user.role !== "OWNER" && user.role !== "ADMIN") redirect("/forbidden");
  return <div className="container-shell py-10"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--muted)] hover:text-[var(--brand)]"><ArrowRight className="h-4 w-4" /> لوحة الإدارة</Link><div className="mt-7 flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[color-mix(in_srgb,var(--brand)_9%,transparent)] text-[var(--brand)]"><Wrench className="h-5 w-5" /></span><div><p className="text-xs text-[var(--muted)]">Tool Registry</p><h1 className="font-display mt-1 text-2xl font-bold">إدارة الأدوات وحدودها</h1></div></div><div className="mt-8 space-y-4">{toolRegistry.map((tool) => <form key={tool.slug} action={updateToolRegistryAction} className="glass-panel rounded-[24px] p-5"><input type="hidden" name="slug" value={tool.slug} /><div className="grid gap-4 xl:grid-cols-[1.3fr_repeat(6,.7fr)_auto] xl:items-end"><div><p className="font-bold">{tool.nameAr}</p><p className="mt-1 text-[10px] text-[var(--faint)]" dir="ltr">{tool.slug}</p></div><label><span className="label">الحالة</span><select name="status" defaultValue={tool.status} className="field min-h-10 py-1.5 text-xs"><option value="active">فعالة</option><option value="external">مزود خارجي</option><option value="coming-soon">قريبًا</option><option value="maintenance">صيانة</option></select></label><label><span className="label">الوصول</span><select name="accessLevel" defaultValue={tool.accessLevel} className="field min-h-10 py-1.5 text-xs"><option value="public">عام</option><option value="member">عضو</option><option value="premium">مدفوع</option></select></label><label><span className="label">حد الزائر</span><input name="anonymousLimit" type="number" defaultValue={tool.anonymousLimit} min={0} className="field min-h-10 py-1.5 text-xs" /></label><label><span className="label">حد العضو</span><input name="memberLimit" type="number" defaultValue={tool.memberLimit ?? 0} min={0} className="field min-h-10 py-1.5 text-xs" /></label><label><span className="label">Credits</span><input name="creditCost" type="number" defaultValue={tool.creditCost} min={0} className="field min-h-10 py-1.5 text-xs" /></label><label><span className="label">الصيانة</span><select name="maintenanceMode" defaultValue={String(tool.maintenanceMode)} className="field min-h-10 py-1.5 text-xs"><option value="false">لا</option><option value="true">نعم</option></select></label><button type="submit" disabled={!realUser} className="btn-primary min-h-10 px-3 text-xs disabled:opacity-45"><Save className="h-3.5 w-3.5" /> حفظ</button></div></form>)}</div>{!realUser && <p className="mt-5 text-sm text-[var(--gold)]">النماذج معطلة في العرض التجريبي، وتصبح كتابتها فعلية بعد ربط قاعدة البيانات.</p>}</div>;
}
