import type { Metadata } from "next";
import { Check, CircleDollarSign, Coins, Gauge, Sparkles } from "lucide-react";

export const metadata: Metadata = { title: "الباقات" };
const plans = [
  { name: "المجانية", icon: Sparkles, description: "للتجربة والاستخدام الشخصي الأساسي.", features: ["ثلاث عمليات للزائر قبل التسجيل", "أدوات المعالجة المحلية", "حساب وسجل استخدام"] },
  { name: "الاحترافية", icon: Gauge, description: "حدود أعلى وأدوات خارجية عند الإطلاق.", features: ["حدود شهرية مرنة", "رصيد Credits", "أدوات أعضاء إضافية"] },
  { name: "الفرق والمطورين", icon: Coins, description: "للشركات والتكاملات البرمجية مستقبلًا.", features: ["API Keys مخزنة بصورة Hash", "حدود لكل مفتاح", "تقارير استخدام موسعة"] },
];
export default function PricingPage() { return <div className="container-shell py-14 sm:py-20"><div className="mx-auto max-w-3xl text-center"><span className="badge text-[var(--gold)]"><CircleDollarSign className="h-3.5 w-3.5" /> بلا أسعار مفروضة الآن</span><h1 className="font-display mt-6 text-3xl font-bold leading-[1.6] sm:text-5xl">نظام باقات مرن قبل وضع الأسعار</h1><p className="mt-5 text-lg leading-9 text-[var(--muted)]">البنية تدعم الحدود اليومية والشهرية والرصيد والتجارب والكوبونات. التسعير التجاري سيُحدد بعد قياس التكلفة والاستخدام الحقيقي.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.map(({ name, icon: Icon, description, features }, index) => <article key={name} className={`glass-panel rounded-[28px] p-7 ${index === 1 ? "border-[var(--line-strong)] lg:-translate-y-3" : ""}`}><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[color-mix(in_srgb,var(--brand)_9%,transparent)] text-[var(--brand)]"><Icon className="h-5 w-5" /></span><h2 className="font-display mt-6 text-xl font-bold">{name}</h2><p className="mt-3 min-h-14 text-sm leading-7 text-[var(--muted)]">{description}</p><div className="hairline my-6" /><ul className="space-y-3">{features.map((feature) => <li key={feature} className="flex gap-2 text-sm text-[var(--muted)]"><Check className="mt-1 h-4 w-4 shrink-0 text-[var(--brand)]" />{feature}</li>)}</ul><span className="mt-7 block rounded-xl border border-[var(--line)] px-4 py-3 text-center text-xs font-bold text-[var(--faint)]">قيد إعداد السياسة السعرية</span></article>)}</div><p className="mx-auto mt-10 max-w-2xl text-center text-sm leading-7 text-[var(--faint)]">لا يوجد دفع أو اشتراك مالي فعّال في هذا الإصدار، والمتجر مخفي بالكامل ما دام Feature Flag معطلًا.</p></div>; }
