"use client";

import { useActionState } from "react";
import { AlertTriangle, Save, Trash2 } from "lucide-react";
import { requestAccountDeletionAction, updateProfileAction } from "@/features/profile/actions";
import { initialProfileState } from "@/features/profile/state";

export function ProfileForms({ name, email, demo }: { name: string; email: string; demo: boolean }) {
  const [profileState, profileAction] = useActionState(updateProfileAction, initialProfileState);
  const [deleteState, deleteAction] = useActionState(requestAccountDeletionAction, initialProfileState);
  return <div className="space-y-6"><form action={profileAction} className="glass-panel rounded-[26px] p-6 sm:p-8"><h2 className="font-display font-bold">البيانات الأساسية</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><label className="label" htmlFor="fullName">الاسم</label><input id="fullName" name="fullName" className="field" defaultValue={name} minLength={2} maxLength={80} required /></div><div><label className="label">البريد الإلكتروني</label><input className="field opacity-65" value={email} disabled dir="ltr" /><p className="mt-2 text-[11px] text-[var(--faint)]">يُغيّر البريد من تدفق تحقق منفصل عند ربط Supabase.</p></div></div>{profileState.message && <p className={`mt-4 text-sm ${profileState.status === "success" ? "text-[var(--success)]" : "text-[var(--danger)]"}`}>{profileState.message}</p>}<button type="submit" disabled={demo} className="btn-primary mt-6 disabled:opacity-45"><Save className="h-4 w-4" /> حفظ التغييرات</button>{demo && <p className="mt-3 text-xs text-[var(--gold)]">الحفظ معطل في الوضع الاستعراضي.</p>}</form><form action={deleteAction} className="rounded-[26px] border border-[color-mix(in_srgb,var(--danger)_25%,transparent)] bg-[color-mix(in_srgb,var(--danger)_5%,transparent)] p-6 sm:p-8"><div className="flex items-start gap-3"><AlertTriangle className="mt-1 h-5 w-5 shrink-0 text-[var(--danger)]" /><div><h2 className="font-display font-bold text-[var(--danger)]">طلب حذف الحساب</h2><p className="mt-2 text-sm leading-7 text-[var(--muted)]">اكتب «حذف حسابي» ثم أرسل الطلب. لا يتم الحذف الفوري دون مراجعة واضحة.</p></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><input name="confirmation" className="field" placeholder="حذف حسابي" autoComplete="off" /><button type="submit" disabled={demo} className="btn-danger shrink-0 disabled:opacity-45"><Trash2 className="h-4 w-4" /> إرسال الطلب</button></div>{deleteState.message && <p className={`mt-4 text-sm ${deleteState.status === "success" ? "text-[var(--success)]" : "text-[var(--danger)]"}`}>{deleteState.message}</p>}</form></div>;
}
